### ISSUE TITLE
889 Tool | USWDS Update from 3.5.0 to 3.6.1

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/889-tool#127]
As an administrator, I want to be sure the 889 website is up to date with the most current version of the USWDS so that I ensure that our site is accessible.

**Acceptance Criteria**
- [ ] Update the version of USWDS being utilized on the site from 3.5.0 to 3.6.1.

**Comment by JennaySDavis** [comment]
**#127 Acceptance Criteria**
 

| Pass/Fail | Description |
| --- | --- | 
| Pass |Update the version of USWDS being utilized on the site from 3.5.0 to 3.6.1. | 


**Comments/Additional Notes**

-   N/A

**ADA Compliance (Automated scan via Chrome Lighthouse)**

- This USWDS library change has been tested for ADA Compliance with USWDS.

Tested By Jennifer Davis on 11/7/2023

**Comment by johnbeallgsa** [comment]
@felder101  Hi Dan, I assume there is nothing to view here to QA the story, as the changes did not impact the look of our site. Correct?

**Comment by felder101** [comment]
@johnbeallgsa That is correct. Just need need to verify none of the page styling has been broken with the upgrade.

**Comment by johnbeallgsa** [comment]
Thanks @felder101 Moving to Done.
